version: '2.0'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgresqlkeystore_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: KeyStoreDB
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    image: mkparkingnav/keystore_app
    container_name: keystore-app_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/KeyStoreDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  postgres-data:
